version: '2'
services:
    smartmeter-app:
        image: smartmeter
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://smartmeter-mysql:3306/smartmeter?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    smartmeter-mysql:
        extends:
            file: mysql.yml
            service: smartmeter-mysql
