version: '2'
services:
    smartmeter-app:
        image: ramazanfirin/smartmeter:test_007042025-2
        environment:
            - SPRING_PROFILES_ACTIVE=dev,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://212.98.224.18:3306/smartmeter2?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Turkey&allowPublicKeyRetrieval=True
            - SPRING_DATASOURCE_USERNAME=ramazan
            - SPRING_DATASOURCE_PASSWORD=ra5699mo
            - JHIPSTER_SLEEP=10
            - JHIPSTER_LOGGING_LOGSTASH_ENABLED=false
            - JHIPSTER_LOGGING_LOGSTASH_HOST=jhipster-logstash
            - JHIPSTER_METRICS_LOGS_ENABLED=false
            - JHIPSTER_METRICS_LOGS_REPORT_FREQUENCY=60
            - APPLICATION_MQTTBROKERURL=tcp://212.98.224.18:1983
        ports:
            - 9091:8091
            - 6000:6000/udp
    #smartmeter-mysql:
    #    image: mysql:5.7.20
    #    environment:
    #        - MYSQL_USER=root
    #        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    #        - MYSQL_DATABASE=smartmeter
    #    command:             mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
#            --explicit_defaults_for_timestamp
    

    #jhipster-elasticsearch:
    #    extends:
    #        file: jhipster-console.yml
    #        service: jhipster-elasticsearch
    #jhipster-logstash:
    #    extends:
    #        file: jhipster-console.yml
    #        service: jhipster-logstash
    #    depends_on:
    #        - jhipster-elasticsearch
    #jhipster-console:
    #    extends:
    #        file: jhipster-console.yml
    #        service: jhipster-console
    #    depends_on:
    #        - jhipster-elasticsearch
    #jhipster-import-dashboards:
    #    extends:
    #        file: jhipster-console.yml
    #        service: jhipster-import-dashboards
    #    depends_on:
    #        - jhipster-elasticsearch
